name: Generate Plugin Info JSON

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version to generate info for'
        required: false
        default: ''

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Ensure we're not in detached HEAD state by checking out the default branch
          ref: ${{ github.event_name == 'release' && 'main' || github.ref }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Generate info.json
        run: php .github/scripts/generate-info-json.php
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MANUAL_VERSION: ${{ github.event.inputs.version }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}

      - name: Commit and push info.json
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Check if there are changes to commit
          if git diff --quiet info.json; then
            echo "No changes to info.json detected"
            exit 0
          fi

          # Add and commit changes
          git add info.json
          git commit -m "Update info.json for latest release"

          # Push changes (specify the branch explicitly)
          git push origin HEAD:${{ github.event_name == 'release' && 'main' || github.ref_name }}
