name: On Release, Build release zip

on: release

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build plugin # Remove or modify this step as needed
      run: |
        composer install --no-dev

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'wp-loupe.zip'
        exclusions: '*.git* .editorconfig composer*'

    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: wp-loupe.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}